"""empty message

Revision ID: b6a80307f251
Revises: 876e921f730d
Create Date: 2024-04-01 17:49:34.592146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6a80307f251'
down_revision: Union[str, None] = '876e921f730d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_to_last_message',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('chat_message_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['chat_message_id'], ['chat_messages.id'], ),
    sa.PrimaryKeyConstraint('chat_id', 'chat_message_id')
    )
    op.add_column('chats', sa.Column('last_update', sa.DateTime(), nullable=True))
    op.drop_constraint(None, 'dialog_images', type_='foreignkey')
    op.create_foreign_key(None, 'dialog_images', 'dialog_messages', ['dialog_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dialog_images', type_='foreignkey')
    op.create_foreign_key(None, 'dialog_images', 'dialogs', ['dialog_id'], ['id'])
    op.drop_column('chats', 'last_update')
    op.drop_table('chat_to_last_message')
    # ### end Alembic commands ###
